### PR TITLE
fix DDTrackCreatorBase::GetTrackStatesAtCalo

### LINKED ISSUE #15: Seg fault caused by invalid track state at calo access
- OS version: SLC6
 - Compiler version: GCC 4.9
 - Package version: afs ILCSoft version HEAD-2017-10-12, DDMarlinPandora commit 2da2612de752c428f326efe8428364811ee1201d
 - Reproduced by: Running the ILDConfig chain on bbuds 3 events
 - Goal: Fix a seg fault related to track state at calorimeter

By running the ILDConfig example with the 3 event example, simulation runs well but reconstruction fails on first event. ROOt gives this stack : 

```shell
===========================================================
#5  0x00007feb6523dbd3 in MarlinTrk::MarlinDDKalTestTrack::findIntersection(DDVMeasLayer const&, TKalTrackSite const&, dd4hep::rec::Vector3D&, double&, int&, int) () at /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-10-12/MarlinTrk/HEAD/src/MarlinDDKalTestTrack.cc:1498
#6  0x00007feb6523dedd in MarlinTrk::MarlinDDKalTestTrack::findIntersection(std::vector<DDVMeasLayer const*, std::allocator<DDVMeasLayer const*> >&, TKalTrackSite const&, dd4hep::rec::Vector3D&, int&, DDVMeasLayer const*&, int) () at /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-10-12/MarlinTrk/HEAD/src/MarlinDDKalTestTrack.cc:1558
#7  0x00007feb6523d8b3 in MarlinTrk::MarlinDDKalTestTrack::intersectionWithLayer(int, TKalTrackSite const&, dd4hep::rec::Vector3D&, int&, DDVMeasLayer const*&, int) () at /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-10-12/MarlinTrk/HEAD/src/MarlinDDKalTestTrack.cc:1463
#8  0x00007feb6523ce67 in MarlinTrk::MarlinDDKalTestTrack::propagateToLayer(int, TKalTrackSite const&, IMPL::TrackStateImpl&, double&, int&, int&, int) () at /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-10-12/MarlinTrk/HEAD/src/MarlinDDKalTestTrack.cc:1313
#9  0x00007feb6523cd3d in MarlinTrk::MarlinDDKalTestTrack::propagateToLayer(int, IMPL::TrackStateImpl&, double&, int&, int&, int) () at /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-10-12/MarlinTrk/HEAD/src/MarlinDDKalTestTrack.cc:1288
#10 0x00007feb667e22ef in DDTrackCreatorBase::GetTrackStatesAtCalo(EVENT::Track*, lc_content::LCTrackParameters&) () at /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-10-12/DDMarlinPandora/HEAD/src/DDTrackCreatorBase.cc:447
#11 0x00007feb667f4440 in DDTrackCreatorILD::CreateTracks(EVENT::LCEvent*) () at /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-10-12/DDMarlinPandora/HEAD/src/DDTrackCreatorILD.cc:254
#12 0x00007feb667ca7a7 in DDPandoraPFANewProcessor::processEvent(EVENT::LCEvent*) () at /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-10-12/DDMarlinPandora/HEAD/src/DDPandoraPFANewProcessor.cc:213
#13 0x00007feb70c67424 in marlin::ProcessorMgr::processEvent(EVENT::LCEvent*) () at /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-10-12/Marlin/HEAD/source/src/ProcessorMgr.cc:470
#14 0x00007feb706c766c in SIO::SIOReader::readStream(int) () at /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-10-12/lcio/HEAD/src/cpp/src/SIO/SIOReader.cc:732
#15 0x00007feb706c73b7 in SIO::SIOReader::readStream() () at /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-10-12/lcio/HEAD/src/cpp/src/SIO/SIOReader.cc:660
#16 0x000000000041a34b in main () at /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-10-12/Marlin/HEAD/source/src/Marlin.cc:509
===========================================================
```

### PR DESCRIPTION
**Pull request by gaede**
BEGINRELEASENOTES
- fix DDTrackCreatorBase::GetTrackStatesAtCalo
    - treat correctly composite spacepoints (from strip stereo layers)
    - protect against initialization error
    - fix logic for backward tracks hitting endcap
 - fixes https://github.com/iLCSoft/DDMarlinPandora/issues/15

ENDRELEASENOTES

### CODE REVIEW

File: src/DDTrackCreatorBase.cc [hunk 1]
```diff
@@ -421,16 +421,34 @@ void DDTrackCreatorBase::GetTrackStatesAtCalo( EVENT::Track *track,
   auto marlintrk = std::unique_ptr<MarlinTrk::IMarlinTrack>(m_trackingSystem->createTrack());
   const EVENT::TrackerHitVec& trkHits = track->getTrackerHits();
   const int nHitsTrack = trkHits.size();
+
   for (int iHit = 0; iHit < nHitsTrack; ++iHit) {
-      marlintrk->addHit(trkHits[iHit]);
+    EVENT::TrackerHit* trkHit = trkHits[iHit] ;
+    if( UTIL::BitSet32( trkHit->getType() )[ UTIL::ILDTrkHitTypeBit::COMPOSITE_SPACEPOINT ]   ){ //it is a composite spacepoint
```
Comment (andresailer) [inline src/DDTrackCreatorBase.cc:427]: Why is this necessary, when we get all the hits from the original track? Weren't the hits of the track already added the same way?

File: src/DDTrackCreatorBase.cc [hunk 2]
```diff
@@ -421,16 +421,34 @@ void DDTrackCreatorBase::GetTrackStatesAtCalo( EVENT::Track *track,
...
+      //Split it up and add both hits to the MarlinTrk
+      const EVENT::LCObjectVec rawObjects = trkHit->getRawHits();
+      for( unsigned k=0; k< rawObjects.size(); k++ ){
+	EVENT::TrackerHit* rawHit = dynamic_cast< EVENT::TrackerHit* >( rawObjects[k] );
```
Comment (andresailer) [inline src/DDTrackCreatorBase.cc]: `static_cast` or check `rawHit` for `nullptr`, or coverity will complain.

File: src/DDTrackCreatorBase.cc [hunk 3]
```diff
@@ -421,16 +421,34 @@ void DDTrackCreatorBase::GetTrackStatesAtCalo( EVENT::Track *track,
   auto marlintrk = std::unique_ptr<MarlinTrk::IMarlinTrack>(m_trackingSystem->createTrack());
   const EVENT::TrackerHitVec& trkHits = track->getTrackerHits();
   const int nHitsTrack = trkHits.size();
+
   for (int iHit = 0; iHit < nHitsTrack; ++iHit) {
-      marlintrk->addHit(trkHits[iHit]);
+    EVENT::TrackerHit* trkHit = trkHits[iHit] ;
+    if( UTIL::BitSet32( trkHit->getType() )[ UTIL::ILDTrkHitTypeBit::COMPOSITE_SPACEPOINT ]   ){ //it is a composite spacepoint
+      //Split it up and add both hits to the MarlinTrk
+      const EVENT::LCObjectVec rawObjects = trkHit->getRawHits();
```
Comment (andresailer) [inline src/DDTrackCreatorBase.cc]: `const&`

File: src/DDTrackCreatorBase.cc (hunk 1 above)
Comment (gaede) [reply src/DDTrackCreatorBase.cc:427]: No, this is what you have to do to pass an lcio::TrackerHit that is a spacepoint made from two strip hits to MarlinTrk - see here:
https://github.com/iLCSoft/MarlinTrk/blob/master/src/MarlinTrkUtils.cc#L236-L260

File: src/DDTrackCreatorBase.cc (hunk 2 above)
Comment (gaede) [reply src/DDTrackCreatorBase.cc]: done.

File: src/DDTrackCreatorBase.cc (hunk 3 above)
Comment (gaede) [reply src/DDTrackCreatorBase.cc]: done.

File: src/DDTrackCreatorBase.cc (hunk 1 above)
Comment (andresailer) [reply src/DDTrackCreatorBase.cc:427]: Then it would be better to change this in the `addHit` function itself. Avoiding all this code duplication
